apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sp9dw3j65-nodejs 
  janus-idp.io/tekton: sp9dw3j65-nodejs
  backstage.io/kubernetes-id: sp9dw3j65-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sp9dw3j65-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml